### ISSUE TITLE
properties dans JavaxSendMailPlugin

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo-extensions#26]
JavaxSendMailPlugin gère un certain nombre de paramètres (host, port, login, pwd ...).
Certains projets peuvent avoir besoin d'autres paramètres dans l'api javax.mail:
https://javaee.github.io/javamail/docs/api/javax/mail/package-summary.html
https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html

Par exemple : debug, timeouts, tls, localhost ...
Il faudrait pouvoir configurer ces paramètres et pas seulement ceux prévus.

**Comment by NPi2Loup** [comment]
When fixed #27 , we added a support of specific connectors. 
We keep provided connectors as simple as possible for the most use case.
If you need more complex connector just add it to your project.
