### ISSUE TITLE
Autocompleter and big list : "Trop d'élément dans le buffer uiObjectByIndex"

### ISSUE THREAD

**Issue by Kaarlak** [vertigo-io/vertigo-extensions#37]
I can't use an autocomplete with a list of 37 000 elements. (Max size 1000)
My list is publish in the context with "publishMdl".

No error when i call the publishMdl method, but when the page loads i get an IllegalStateException :
java.lang.IllegalStateException: Trop d'élément dans le buffer uiObjectByIndex de la liste de ...

In AbstractUiListUnmodifiable, in the method UiObject<O> get(final int index), line 143.

**Comment by mlaroche** [comment]
You're right, the UiMdList should implement it's own tranformation to be given to the client, not the basic iteration over the list of elements.
